// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ImageScore",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "ImageScore",
            targets: ["AppModule"],
            bundleIdentifier: "com.developer.gavinxiang.ImageScore",
            teamIdentifier: "ZA2PCCN27W",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .moon),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "git@github.com:ZipArchive/ZipArchive.git", "2.6.0"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "ZipArchive", package: "ziparchive")
            ],
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)